# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

name: $(BuildDefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  buildConfiguration: 'Release'
  azureConnection: 'azure-cicd-demo-sp'
  location: 'southeastasia'
  prefix: "ayuina-devops"


trigger:
- dev

stages:

- stage:
  displayName: "Deploy Infrastructure"
  jobs:
  - job:
    displayName: "Deploy ARM Template"
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: '$(azureConnection)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(prefix)-rg'
        location: '$(location)'
        templateLocation: 'https://raw.githubusercontent.com/ayuina/azure-function-cicd/$(Build.SourceBranchName)/azuredeploy.json'
        deploymentMode: 'Incremental'







