# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

name: $(BuildDefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: AAD_SP
  - name: buildConfiguration
    value: 'Release'
  - name: azureConnection
    value: 'azure-cicd-demo-sp'
  - name: location
    value: 'southeastasia'
  - name: prefix
    value: "ayuina"


trigger:
- dev

stages:

- stage:
  displayName: "Build Stage"
  jobs:
  - job:
    displayName: "Creating artifacts"
    pool:
      vmImage: 'windows-2019'
    steps:

    - script : tree /F

    - task: DotNetCoreCLI@2
      displayName: 'Restore Package'
      inputs:
        command: restore
        projects: '**/image-processor.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build project'
      inputs:
        projects: '**/image-processor.csproj'
        arguments: '--output $(Build.BinariesDirectory)/publish_output --configuration $(buildConfiguration)'

    - task: ArchiveFiles@2
      displayName: 'Zip for Functions'
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)/publish_output/'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/arm'
      inputs:
        contents: '**/*.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifactName: drop
        targetPath: '$(Build.ArtifactStagingDirectory)'

- stage:
  displayName: "Deploy Infrastructure"
  jobs:
  - job:
    displayName: "Deploy ARM Template"
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current' 
        artifactName: drop
        targetPath: './drop' 

    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: '$(azureConnection)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(prefix)-rg'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'azuredeploy.json'
        overrideParameters: '-location $(location) -prefix $(prefix)'
        deploymentMode: 'Incremental'

    - task: AzureFunctionApp@1
      displayName: Azure Function App Deploy
      inputs:
        azureSubscription: '$(azureConnection)'
        appType: functionApp
        appName: '$(prefix)-func'
        package: './drop/*.zip'
      
    - script: 'set'

    - script: dir 

    - task: AzurePowerShell@4
      inputs:
        azureSubscription: '$(azureConnection)'
        scriptType: 'filePath' # Optional. Options: filePath, inlineScript
        scriptPath: './setup-eventsubscription.ps1'
        
        
        
